@api = http://localhost:4000/api/estilos

{{api}}

### add a estilo
POST http://localhost:4000/api/estilos

Content-Type: application/json


{
    "estilo": "400a",
    "nombreestilo": "some estilo4",
    "linea": "linea 4",
    "horma": "horma 4",
    "molde": "molde 4",
    "estado": "Activo",
    "fotografia": "foto4.jpg",
    "observaciones": "observaciones 4",
    "status": "Activo"
}

### get estilo
{{api}}/3

### delete estilo 
DELETE {{api}}/123

### get count
{{api}}/count

### update
PUT {{api}}/137
Content-Type: application/json

{
    "estilo": "400a",se uede hacer 
    "nombreestilo": "some estilo4",
    "linea": "linea 4",
    "horma": "horma 4",
    "molde": "molde 4",
    "estado": "Activo",
    "fotografia": "foto4.jpg",
    "observaciones": "observaciones 4",
    "status": "Activo"
}