const selectOptions = {
  0: 'Vigente',
  1: 'Descontinuado',
};

const dataestilos = [
  {
    id: 1,
    estilo: '300',
    nombre: 'Vegas',
    linea: 'infinity',
    horma: 'H500',
    molde: 'M100',
    fotografia: 'foto1.jpg',
    estado: selectOptions[0],
  },
  {
    id: 2,
    estilo: '301',
    nombre: 'California',
    linea: 'Wata',
    horma: 'H500',
    molde: 'M200',
    fotografia: 'foto2.jpg',
    estado: selectOptions[1],
  },
  {
    id: 3,
    estilo: '400',
    nombre: 'Estilo 400',
    linea: 'Wata',
    horma: 'Emri Akça',
    molde: '-',
    fotografia: 'foto3.jpg',
    estado: selectOptions[1],
  },
  {
    id: 4,
    estilo: '410',
    nombre: 'Estilo 410',
    linea: 'Moldavia',
    horma: 'H500',
    molde: 'M100',
    fotografia: 'foto4.jpg',
    estado: selectOptions[1],
  },
  {
    id: 5,
    estilo: '100',
    nombre: '100 CHAROL',
    linea: 'Rio Grande',
    horma: 'H100',
    molde: 'M200',
    fotografia: 'foto5.jpg',
    estado: selectOptions[1],
  },
  {    
    id: 6,
    estilo: '101',
    nombre: '101 Rojo',
    linea: 'Price',
    horma: 'H100',
    molde: 'M500',
    fotografia: 'foto6.jpg',
    estado: selectOptions[1],
  },
  {
    id: 7,
    estilo: '102',
    nombre: '101 Rojo2',
    linea: 'Price',
    horma: 'H100',
    molde: 'M500',
    fotografia: 'foto7.jpg 107',
    estado: selectOptions[1],
  },
  {
    id: 8,
    estilo: '103',
    nombre: '103 Rojo',
    linea: 'Price',
    horma: 'H100',
    molde: 'M500',
    fotografia: 'foto1.jpg',
    estado: selectOptions[1],
  },
  {
    id: 9,
    estilo: '104',
    nombre: '104 Rojo',
    linea: 'Price',
    horma: 'H100',
    molde: 'M500',
    fotografia: 'foto2.jpg',
    estado: selectOptions[1],
  },
  {
    id: 10,
    estilo: '105',
    nombre: '105 Rojo',
    linea: 'Price',
    horma: 'H100',
    molde: 'M500',
    fotografia: 'foto4.jpg',
    estado: selectOptions[1],
  },
  {
    id: 11,
    estilo: '106',
    nombre: '106 Rojo 6',
    linea: 'Price',
    horma: 'H100',
    molde: 'M500',
    fotografia: 'foto5.jpg',
    estado: selectOptions[1],
  },
];
// eslint-disable-next-line
export default dataestilos;
